### ISSUE TITLE
[Mirror Request] BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [ZJUSCT/mirror-issues#1]
## intro

- name: `BioArchLinux`
- intro_link: <bioarchlinux.org>
- storage_link: <repo.bioarchlinux.org>
- licence: AGPL
- size: 30G

## descrption and reasons

Arch Community for Biologists & Arch Repository for Biological Software, make it easier to perform bioinformatics analysis
```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```

**Comment by determ1ne** [comment]
Closed as not planned.
