### ISSUE TITLE
[Mirror Request] openSUSE & Packman

### ISSUE THREAD

**Issue by Ratizux** [ZJUSCT/mirror-issues#11]
http://download.opensuse.org/
http://packman.links2linux.org/

**Comment by RalXYZ** [comment]
After internal discussions, we believe that these images have a huge impact and have decided to support it. We will proceed in the following three steps:  
The following status information will be updated according to the latest developments.

### openSUSE
- [x] Synchronize the image
- [x] Add image documentation https://github.com/ZJUSCT/mirror-front/pull/53
- [x] Apply to become an official image

### packman
- [x] Synchronize the image
- [x] Add image documentation https://github.com/ZJUSCT/mirror-front/pull/53

After these steps have been completed with clear conclusions, we will close this issue.
