### ISSUE TITLE
[Mirror Request] buildroot dependencies.

### ISSUE THREAD

**Issue by bittervan** [ZJUSCT/mirror-issues#15]
When using buildroot to generate rootfs for embedded systems, these download sites are required:
1. Back up site, fallback if other sites are not available: http://sources.buildroot.net
2. The Linux kernel source code, already provided by the ZJU mirrors
3. The GNU mirror, already provided by the ZJU mirrors
4. The LuaRocks mirror: https://luarocks.cn
5. The CPAN, already provided by the ZJU mirrors

**Comment by determ1ne** [comment]
在校园网络下访问 sources.buildroot.net 没有困难， buildroot 也没有提供适合镜像的基础设施/镜像方法。

暂时没有必要设立该镜像。
