### ISSUE TITLE
[Mirror Requests] Bioconductor

### ISSUE THREAD

**Issue by WatchmanGu** [ZJUSCT/mirror-issues#16]
可否镜像Bioconductor呢？对于农生医研究生来讲，有不少生信分析需要的R包在Bioconductor上。
https://mirrors.tuna.tsinghua.edu.cn/help/bioconductor/

**Comment by RalXYZ** [comment]
我们内部讨论了一下，认为这个镜像在生信领域存在一定的重要性，决定进行支持。
我们会按下面三步走：
- [x] 同步镜像
- [x] 添加镜像文档  https://github.com/ZJUSCT/mirror-front/pull/58
- [x] 申请成为官方镜像

这三步都有明确结论以后，我们再把这个 issue 关闭。

**Comment by RalXYZ** [comment]
@WatchmanGu 我们这边的工作都完成了，辛苦你试下镜像是否可用。
文档：https://mirrors.zju.edu.cn/docs/bioconductor/

**Comment by WatchmanGu** [comment]
感谢！😀
改了~/.Rprofile，找了个没安装过的Bioconductor包试了下，发现校园内网下不能正常使用BiocManager装包。
长时间等待无响应。
似乎是因为 BiocManager::install("xxxx")  还是会尝试访问校外网络
```
> BiocManager::install("clusterProfiler")
Warning message:
In file(con, "r") : 
URL 'https://bioconductor.org/config.yaml': Timeout of 60 seconds was reached

```

**Comment by yzhblind** [comment]
> 感谢！😀 改了~/.Rprofile，找了个没安装过的Bioconductor包试了下，发现校园内网下不能正常使用BiocManager装包。 长时间等待无响应。 似乎是因为 BiocManager::install("xxxx") 还是会尝试访问校外网络
> 
> ```
> > BiocManager::install("clusterProfiler")
> Warning message:
> In file(con, "r") : 
> URL 'https://bioconductor.org/config.yaml': Timeout of 60 seconds was reached
> ```

您好，那请问直接在终端输入`options(BioC_mirror="https://mirrors.zju.edu.cn/bioconductor")`是否可用呢

**Comment by WatchmanGu** [comment]
> > 感谢！😀 改了~/.Rprofile，找了个没安装过的Bioconductor包试了下，发现校园内网下不能正常使用BiocManager装包。 长时间等待无响应。 似乎是因为 BiocManager::install("xxxx") 还是会尝试访问校外网络
> > ```
> > > BiocManager::install("clusterProfiler")
> > Warning message:
> > In file(con, "r") : 
> > URL 'https://bioconductor.org/config.yaml': Timeout of 60 seconds was reached
> > ```
> 
> 您好，那请问直接在终端输入`options(BioC_mirror="https://mirrors.zju.edu.cn/Bioconductor")`是否可用呢

出现的情况是一样的。
![image](https://user-images.githubusercontent.com/27331265/232129413-58b459f2-8853-41d2-8b49-68ff344843cd.png)
 我尝试谷歌了一下，似乎是由于镜像上没有config.yaml➡Bioconductor/BiocManager/issues/75

**Comment by RalXYZ** [comment]
@WatchmanGu 我看了下官方的 issue，[纯离线使用已经被 BiocManager 1.30.12 支持了](https://github.com/Bioconductor/BiocManager/issues/75#issuecomment-812611775)。你使用的 BiocManager 高于这个版本么？如果没有到这个版本，可以考虑先升级。

如果版本正确的话，我看到[官方文档里有关于离线使用的配置](https://github.com/Bioconductor/BiocManager/blob/6e4052750234b643c5acbaa1b062fb10f1c332e8/vignettes/BiocManager.Rmd#L262)。这些在我们镜像站的文档里未提及，辛苦你跟着官方文档里相关章节的步骤走一遍，再看看有没有问题。

**Comment by WatchmanGu** [comment]
感谢！我下载了config.yaml放服务器上，在~/.Rprofile里按照官方文档添加对应路径，就可以了。
```{r, eval = FALSE}
    options(
        BIOCONDUCTOR_CONFIG_FILE = "file:///path/to/config.yaml"
    )

**Comment by RalXYZ** [comment]
@WatchmanGu 好诶，可用了就好😆
顺便，不知道你是否方便帮我们个忙。我们[当前的文档](https://github.com/ZJUSCT/mirror-front/blob/main/docs/zh/bioconductor.mdx)并没有描述离线使用的方案，而你实践了这个过程。不知道你是否可以把你**离线使用 Bioconductor 的操作过程**，一步步地写出来，我们添加到文档里，这样也方便后面的同学解决这一问题。

如果可以的话，你直接在这个 issue 下把操作过程写出来即可，我们会帮你 commit 进镜像站文档，并且算作你的 credit。

**Comment by WatchmanGu** [comment]
好的。
添加完浙大镜像后。由于BiocManager需要一个yaml配置文件，以进行Bioconductor版本验证。对于浙大内网服务器，可以自行从https://bioconductor.org/config.yaml 下载一份config.yaml并上传到服务器上。然后，将config.yaml的路径添加到.Rprofile中：
` options(BIOCONDUCTOR_CONFIG_FILE = "file:///path/to/config.yaml")`
当BiocManager更新版本时，需要再从 https://bioconductor.org/config.yaml  手动下载一份新版本，进行同样的操作。

**Comment by WatchmanGu** [comment]
@RalXYZ 对了，刚想到，或许浙大镜像站可以同样同步镜像config.yaml？这样使用bioconductor时只要修改.Rprofile设置为镜像站的路径就可以了。
 `options(BIOCONDUCTOR_CONFIG_FILE = "https://path/to/mirror/config.yaml")`

**Comment by RalXYZ** [comment]
> 好的。 添加完浙大镜像后。由于BiocManager需要一个yaml配置文件，以进行Bioconductor版本验证。对于浙大内网服务器，可以自行从https://bioconductor.org/config.yaml 下载一份config.yaml并上传到服务器上。然后，将config.yaml的路径添加到.Rprofile中： ` options(BIOCONDUCTOR_CONFIG_FILE = "file:///path/to/config.yaml")` 当BiocManager更新版本时，需要再从 https://bioconductor.org/config.yaml 手动下载一份新版本，进行同样的操作。

诶，只要升级版本，配置文件里的所有内容就会被覆盖？还需要用户重新手动配置？

**Comment by WatchmanGu** [comment]
> > 好的。 添加完浙大镜像后。由于BiocManager需要一个yaml配置文件，以进行Bioconductor版本验证。对于浙大内网服务器，可以自行从https://bioconductor.org/config.yaml 下载一份config.yaml并上传到服务器上。然后，将config.yaml的路径添加到.Rprofile中： ` options(BIOCONDUCTOR_CONFIG_FILE = "file:///path/to/config.yaml")` 当BiocManager更新版本时，需要再从 https://bioconductor.org/config.yaml 手动下载一份新版本，进行同样的操作。
> 
> 诶，只要升级版本，配置文件里的所有内容就会被覆盖？还需要用户重新手动配置？

需要用户手动配置。我前面表述不太对，应该是bioconductor更新版本时要更新config.yaml。

**Comment by RalXYZ** [comment]
@WatchmanGu 提供的文档已被浙大镜像站和 [mirrorz-help 项目](https://github.com/mirrorz-org/mirrorz-help)合入， git commit author 署名为 @WatchmanGu

https://github.com/ZJUSCT/mirror-front/pull/60
https://github.com/mirrorz-org/mirrorz-help/pull/90

非常感谢
