### ISSUE TITLE
[Bug Report] npm镜像503错误

### ISSUE THREAD

**Issue by ChongChengAC** [ZJUSCT/mirror-issues#17]
安装reveal-md（npm install reveal-md -g）时报错：
```
npm ERR! 503 Service Temporarily Unavailable - GET https://mirrors.zju.edu.cn/npm/<每次都不一样>
```

**Comment by determ1ne** [comment]
无法复现。请提供更详细的信息（如网络环境、系统环境变量、npm config、npm install 时使用 --loglevel verbose 的截图）。

**Comment by ChongChengAC** [comment]
npm config ls:
```ini
; "user" config from /home/qiu/.npmrc

registry = "https://mirrors.zju.edu.cn/npm" 

; node bin location = /usr/bin/node
; node version = v19.8.1
; npm local prefix = /home/qiu
; npm version = 8.19.2
; cwd = /home/qiu
; HOME = /home/qiu
; Run `npm config ls -l` to show all defaults.
```

`--loglevel verbose`输出：
![image](https://user-images.githubusercontent.com/63496547/231115914-498dbf21-dc5b-416f-a115-5b5c49e61fc0.png)

网络环境：实验室有线网静态IP（在另一台设备上用无线网也会报错）
系统环境变量：太多了，总之没有设置http_proxy和https_proxy

**Comment by determ1ne** [comment]
并发连接限制的原因，已经修复
