### ISSUE TITLE
[Mirror Request] Linux Mint packages

### ISSUE THREAD

**Issue by futuretech6** [ZJUSCT/mirror-issues#19]
https://mirrors.tuna.tsinghua.edu.cn/help/linuxmint/

**Comment by RalXYZ** [comment]
After internal discussion, we believe that Linux Mint has a certain influence, therefore, we will provide a mirror of its software repository. We will proceed in the following steps:  

- [x] Synchronize the repository
- [x] Add documentation 
- [x] Apply to become an official mirror

The status information above will be updated in real time according to our progress.

**Comment by RalXYZ** [comment]
@futuretech6  We have completed all our work here. Could you please test if the Linux Mint mirror is usable?

repo: https://mirrors.zju.edu.cn/linuxmint/
docs: https://mirrors.zju.edu.cn/docs/linuxmint/

**Comment by futuretech6** [comment]
It works perfectly, thanks a lot.
