### ISSUE TITLE
[镜像请求] 请求添加 ImmortalWrt 镜像

### ISSUE THREAD

**Issue by douglarek** [ZJUSCT/mirror-issues#22]
### 先决条件 / Prerequisites

- [X] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/ZJUSCT/mirror-issues/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 项目简介 / Introduction

ImmortalWrt 是 OpenWrt 的一个第三方分支，主要针对国人用户开发，提供更多的本地化软件包和设备支持。

项目地址： https://github.com/immortalwrt

### 上游地址与镜像方法 / Upstream & Method

下载地址： https://downloads.immortalwrt.org/

镜像方法：

```
env RSYNC_PASSWORD="immortalwrt-org" rsync -4ahv --delete-delay "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" "immortalwrt/"
```

### 镜像大小 / Size

~ 560 GB

### 备注 / Notes

其他已通过镜像讨论：
* https://github.com/JLULUG/issues/issues/8
* https://github.com/sjtug/mirror-requests/issues/319

**Comment by RalXYZ** [comment]
我们认真阅读了相关 issue，并与 @1715173329 进行了讨论，得出以下结论：
1. 在境内， ImmortalWrt 的使用量暂时不大，且已被 NJU、SJTU、PKU 镜像，带宽资源已经足够使用
2. 目前，浙江大学校内并未报告有对 ImmortalWrt 的使用需求

因此，我们决定，**暂不跟进**这一镜像。如果上述二者任一发生变化，我们会继续跟进这一镜像。
