### ISSUE TITLE
[Mirror Requests] CentOS epel 6以下版本镜像缺失

### ISSUE THREAD

**Issue by Wzuoqi** [ZJUSCT/mirror-issues#27]
服务器为Red Hat Enterprise Linux Server release 6.8 (Santiago)，需要epel 6的版本
但目前 https://mirrors.zju.edu.cn/epel/6/ 下仅有readme文件，希望能像7一样补全

**Comment by determ1ne** [comment]
epel 6 已被上游移除，不存在文件缺失。暂无计划镜像 epel archive 。

**Comment by Wzuoqi** [comment]
> epel 6 已被上游移除，不存在文件缺失。暂无计划镜像 epel archive 。

好的，感谢
