### ISSUE TITLE
[Mirror Request] docker hub

### ISSUE THREAD

**Issue by Sha1rholder** [ZJUSCT/mirror-issues#29]
Only Trusted Content plz
![image](https://github.com/ZJUSCT/mirror-issues/assets/96712109/32e9e0b5-003f-4dfe-8dcb-2b2957201879)

**Comment by determ1ne** [comment]
docker hub 无法同步，只能反代
由于带宽受限，暂时不会考虑开更多反代服务

**Comment by paulzhn** [comment]
有无可能采用白名单的机制，先同步一批镜像呢？
