### ISSUE TITLE
[Mirror Requests] homebrew & homebrew-bottles

### ISSUE THREAD

**Issue by cyoahs** [ZJUSCT/mirror-issues#3]
Hello!

`homebrew` is a popular opensource package manager for macOS, and `homebrew-bottles` is for pre-built binaries. The direct connection to the official server is unstable, and most people use the mirror from tuna. I hope we can use it from our own mirror.

Reference links from tuna:
https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/

**Comment by iamNCJ** [comment]
Hi! `homebrew` is now available on ZJU mirror, and `homebrew-bottles` is proxy-cached from tuna. We are still working on documents, but now you can simply use our mirror by swapping the URLs in tuna's doc to `mirrors.zju.edu.cn`.

**Comment by iamNCJ** [comment]
docs now available at https://mirrors.zju.edu.cn/docs/homebrew.git/
