### ISSUE TITLE
 [Mirror Request] Rust crates.io 稀疏索引

### ISSUE THREAD

**Issue by du33169** [ZJUSCT/mirror-issues#30]
Rust的crates.io源在一年前就增加了[稀疏索引和HTTP支持](https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html)，在更新索引时具有更快的速度和更小的硬盘缓存文件占用
大部分镜像站也已经同步更新，例如清华镜像站的[crates.io-index/](https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index/)
浙大镜像目前似乎仍然只有[不支持稀疏索引的git镜像](https://mirrors.zju.edu.cn/docs/crates.io-index.git/)

**Comment by determ1ne** [comment]
已完成同步，供测试 https://mirrors.zju.edu.cn/crates.io-index/

**Comment by du33169** [comment]
感谢，测试可用
