### ISSUE TITLE
[Bug Report] PyPi 包版本缺失

### ISSUE THREAD

**Issue by Geniucker** [ZJUSCT/mirror-issues#31]
即使最近成功同步时间较近，还是有包没有同步上

以 `pymobiledevice3` 为例，
https://mirrors.zju.edu.cn/pypi/web/simple/pymobiledevice3/ 中没有 2.43和2.44版本
与之相比清华源https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/pymobiledevice3/ 是有的

这两个版本的发布时间参考：https://github.com/doronz88/pymobiledevice3/releases

**Comment by iamNCJ** [comment]
Thanks for reporting, we are working on this issue.

**Comment by determ1ne** [comment]
Similar to https://github.com/pypa/bandersnatch/issues/1633

**Comment by determ1ne** [comment]
已解决
