### ISSUE TITLE
[Bug Report] Docker CE网页无内容

### ISSUE THREAD

**Issue by ChongChengAC** [ZJUSCT/mirror-issues#34]
![image](https://github.com/user-attachments/assets/562b71ec-dd07-484c-87ce-9dfeba977bc6)
Docker CE (https://mirrors.zju.edu.cn/docs/docker-ce/) 网页是空的，没有内容：
![image](https://github.com/user-attachments/assets/83e7cca9-e115-4c59-b436-c37aa233951a)

**Comment by RalXYZ** [comment]
这一问题，四天前已在 https://github.com/ZJUSCT/mirror-front/pull/101 中修复源代码。
刚刚完成部署，目前线上也已修复。
感谢
