### ISSUE TITLE
[Mirror Request] FreeBSD

### ISSUE THREAD

**Issue by yzyDavid** [ZJUSCT/mirror-issues#4]
https://docs.freebsd.org/en/books/handbook/mirrors/
https://docs.freebsd.org/en/articles/hubs/

**Comment by RalXYZ** [comment]
Currently, the number of FreeBSD users is very small and http://freebsd.cn can already provide high-quality mirror services for users in mainland China. Therefore, we will not consider including FreeBSD-related mirrors in the short term.
