### ISSUE TITLE
The openEuler mirrors will update the rsync address

### ISSUE THREAD

**Issue by nicliuqi** [ZJUSCT/mirror-issues#8]
Hi, we have registered a new rsync address for the openEuler mirrors, and the old one will be replaced.

If your site is still using rsync://121.36.97.194/ as the rsync address, please change it to rsync://repo.openeuler.openatom.cn/openeuler/ and inform us. Thank you!

Synchronization command: rsync rsync://repo.openeuler.openatom.cn/openeuler/

Best regards,
Infrastructure team, openEuler community

**Comment by determ1ne** [comment]
Hi, is there any official documentation explaining this change?

**Comment by nicliuqi** [comment]
There's no clear statement about the change, but you could visit our mirror list https://www.openeuler.org/zh/mirror/list/ , and then you will find that the rsync address of openEuler-Beijing has been updated to rsync://repo.openeuler.openatom.cn/openeuler/ .
We will consider the rsync address of openEuler-Beijing as the recommended address, and emphasize it on the website.

**Comment by nicliuqi** [comment]
If you have any doubts, you can also go to https://gitee.com/openeuler/infrastructure to contact us through issue.

**Comment by determ1ne** [comment]
Rsync remote has changed to `repo.openeuler.openatom.cn`.

**Comment by nicliuqi** [comment]
^ - ^  thks
